HTTP_GET = 'GET'
HTTP_POST = 'POST'
HTTP_PUT = 'PUT'
HTTP_HEAD = 'HEAD'
HTTP_DELETE = 'DELETE'
HTTP_CONNECT = 'CONNECT'
HTTP_OPTIONS = 'OPTIONS'
HTTP_TRACE = 'TRACE'
HTTP_PATCH = 'PATCH'

# content types

CONTENT_TYPE = 'Content-Type'


